### ISSUE TITLE
Implement Cairo Function for Nostr Signature Verification

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#1]
## Description
Implement a Cairo function to verify Nostr signatures. This function will be a crucial component for integrating Nostr into our Starknet-based decentralized social platform.

## Tasks
- [ ] Research Nostr signature format and requirements.
- [ ] Define the Cairo function interface.
- [ ] Implement the signature verification logic in Cairo.
- [ ] Write unit tests for the Cairo function.

**Comment by sprtd** [comment]
@AbdelStark Can this task be assigned to me. Thank you

**Comment by Immanuelolivia1** [comment]
Hi @AbdelStark i would like to work on this

**Comment by AbdelStark** [comment]
> @AbdelStark Can this task be assigned to me. Thank you

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by AbdelStark** [comment]
> Hi @AbdelStark i would like to work on this

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by AbdelStark** [comment]
Fixed by #8
