### ISSUE TITLE
Develop Starknet Account Contract Using Nostr Keypair

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#2]
## Description
Create a Starknet smart contract that uses Nostr keypairs for account control. This contract will serve as the backbone for user interactions on our platform, enhancing security and decentralization.

## Tasks
- [ ] #14
- [ ] Implement the contract using Cairo.
- [ ] Test integration with Nostr keypairs.
- [ ] Document the usage and deployment process.

**Comment by sprtd** [comment]
@AbdelStark I would like to work on this

**Comment by AbdelStark** [comment]
> @AbdelStark I would like to work on this

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by maciejka** [comment]
Subtasks moved to #5
