### ISSUE TITLE
Build Frontend for Nostr Signature Signing and Verification

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#3]
## Description

Develop a simple frontend interface that allows users to sign and verify messages using Nostr-compatible browser extensions like Flamingo or nos2x.

The webapp has been initiated in `joyboy-webapp` directory. It currently has simple signing of messages using Nostr NIP-07 compatible extensions (tested with `nos2x` and `keys.band`).

## Tasks
- [ ] Design the UI/UX for signing and verification.
- [ ] Implement the React components.
- [ ] Integrate with browser extensions via API.
- [ ] Conduct end-to-end testing

**Comment by Ayoazeez26** [comment]
I would like to work on this issue

**Comment by AbdelStark** [comment]
> I would like to work on this issue

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by Ayoazeez26** [comment]
@AbdelStark  alright, thank you. Please keep me updated
