### ISSUE TITLE
Design and Implement Joyboy Landing Page

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#4]
## Description
Create an engaging and informative landing page for the Joyboy platform. The page should introduce the platform, its features, and how to get started.

## Tasks
- [ ] Draft the content for the landing page.
- [ ] Design the page layout and style.
- [ ] Implement the page in HTML/CSS with React.
- [ ] Optimize the page for SEO and mobile devices.

**Comment by Joy-Adah** [comment]
Hi @AbdelStark is this up for contribution? If it is, I am interested in this issue.

**Comment by Calebux** [comment]
Hi @AbdelStark i want to design this landing page and also develop the content. i have experience in web 3 designs and give my best to this project.

**Comment by AbdelStark** [comment]
> Hi @AbdelStark is this up for contribution? If it is, I am interested in this issue.

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by AbdelStark** [comment]
> Hi @AbdelStark i want to design this landing page and also develop the content. i have experience in web 3 designs and give my best to this project. **Here are samples** https://www.figma.com/proto/MAu4m8dxXKQxhA3qI7wjLv/Looop?type=design&node-id=14-37&t=azKcUd5maQysTYmb-0&scaling=min-zoom&page-id=12%3A2

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by SiteBldrs** [comment]
Hi @AbdelStark, I'm thrilled about the chance to assist in bringing your project for the Joyboy platform to reality, having seen it. With my background in web design, React development, and content creation, I can create a captivating landing page that clearly conveys the features and advantages of the platform. Together, let's produce something useful and influential. eager to collaborate with you!

**Comment by ayushtom** [comment]
👋 i can also help on this with others!

**Comment by Calebux** [comment]
I'll like to work on this @AbdelStark

**Comment by Oshioke-Salaki** [comment]
Hello can i work on this?

**Comment by PhavourIB** [comment]
I will work on this with the other designers

**Comment by DanielEmmanuel1** [comment]
Hello @AbdelStark Is this project still up for contribution?
I would really love to give it a shot.
Although this will be my first contribution to OD Hack, I'm really confident in my abilities to deliver a fully functional and responsive landing page

**Comment by Osatuyi** [comment]
@AbdelStark I'll like to draft the content for the landiing page when this issue kicks off. I'm a uiux designer. I can get this done excellently.

**Comment by devcollinss** [comment]
@AbdelStark  is this issue still available?

**Comment by jedstroke** [comment]
@AbdelStark Yo, I could help speed up dev with the existing assignees

**Comment by Ejembiii** [comment]
@AbdelStark If the design layout for the landing page is still open, I would love to work on it

**Comment by CollinsC1O** [comment]
hi @AbdelStark I will also love to work on this

**Comment by jorgezerpa** [comment]
Yo! @AbdelStark I would like to be assigned to this task. 

I have years of experience with react native and web dev, and this issue looks perfect as an introduction to the project to then work on other issues.

**Comment by JoshdfG** [comment]
can i assist with anything if this is still open??
