### ISSUE TITLE
Build Full Nostr Client Application with Starknet Support

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#6]
### Description
Develop a comprehensive Nostr client that fully integrates Starknet features, offering a robust platform for decentralized social interactions.

### Tasks
- [ ] Plan the application architecture integrating Nostr and Starknet.
- [ ] Implement the client functionality.
- [ ] Ensure compatibility with existing Nostr and Starknet systems.
- [ ] Perform comprehensive functional and stress testing.

**Comment by Xaxxoo** [comment]
Hi @AbdelStark, May I take this please? I will love the challenge.

**Comment by AbdelStark** [comment]
> Hi @AbdelStark, May I take this please? I will love the challenge.

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by Xaxxoo** [comment]
Hi @AbdelStark, May I take this please? I will love the challenge.

**Comment by Xaxxoo** [comment]
Is this still assigned to me? Can I go on and work on it ?

**Comment by AbdelStark** [comment]
> Is this still assigned to me? Can I go on and work on it ?

Sorry I found someone who will initiate the work here. We wont open the contributions to the app initially, want to have solid foundations on the app before onboarding contributors. Should be good in 1-2 weeks.

**Comment by martinvibes** [comment]
hey i would really wan to contribute to this

**Comment by josephchimebuka** [comment]
@AbdelStark is the person assigned to this task still on it?... I could still help u and the person out though
